import { Recipe } from "../types/recipe";

export const fetchRecipes = async (): Promise<Recipe[]> => {
  return [
    {
      meal_type: "breakfast",
      recipe_name: "Słodki omlet kokosowy z bananem i jagodami",
      ingredients: [
        { name: "Jajo kurze", quantity: "150 g", measure: "3 średnie sztuki" },
        { name: "Mąka kokosowa", quantity: "50 g", measure: "50 g" },
      ],
      instructions: [
        "W misce roztrzepać jajka z mąką kokosową, napojem i szczypką soli, aż masa będzie jednolita.",
        "Na rozgrzaną patelnię z oliwą wylać masę jajeczną.",
        "Na wierzchu ułożyć plasterki banana i jagody.",
      ],
      calories: 695,
      protein: 29,
      fat: 36,
      carbs: 66,
      incomplete: false,
    },
    {
      meal_type: "lunch",
      recipe_name: "Grillowany kurczak z warzywami",
      ingredients: [
        { name: "Pierś z kurczaka", quantity: "200 g", measure: "1 sztuka" },
        { name: "Papryka czerwona", quantity: "100 g", measure: "1 sztuka" },
        { name: "Cukinia", quantity: "150 g", measure: "0.5 sztuki" },
        { name: "Oliwa z oliwek", quantity: "10 ml", measure: "1 łyżka" },
      ],
      instructions: [
        "Kurczaka przyprawić solą, pieprzem i oliwą.",
        "Grillować kurczaka oraz pokrojone warzywa na średnim ogniu przez 10 minut.",
        "Podawać na ciepło z sosem jogurtowym.",
      ],
      calories: 450,
      protein: 55,
      fat: 12,
      carbs: 15,
      incomplete: false,
    },
    {
      meal_type: "dinner",
      recipe_name: "Sałatka z tuńczykiem i jajkiem",
      ingredients: [
        {
          name: "Tuńczyk w sosie własnym",
          quantity: "120 g",
          measure: "1 puszka",
        },
        { name: "Jajo kurze", quantity: "100 g", measure: "2 średnie sztuki" },
        { name: "Sałata lodowa", quantity: "50 g", measure: "kilka liści" },
        { name: "Oliwa z oliwek", quantity: "10 ml", measure: "1 łyżka" },
      ],
      instructions: [
        "Jajka ugotować na twardo i pokroić w ćwiartki.",
        "Tuńczyka odsączyć z zalewy.",
        "Wszystkie składniki połączyć, skropić oliwą i podawać.",
      ],
      calories: 350,
      protein: 40,
      fat: 18,
      carbs: 8,
      incomplete: false,
    },
    {
      meal_type: "lunch",
      recipe_name: "Makaron pełnoziarnisty z pesto i kurczakiem",
      ingredients: [
        {
          name: "Makaron pełnoziarnisty",
          quantity: "100 g",
          measure: "1 porcja",
        },
        { name: "Pierś z kurczaka", quantity: "150 g", measure: "1 sztuka" },
        { name: "Pesto bazyliowe", quantity: "30 g", measure: "2 łyżki" },
      ],
      instructions: [
        "Makaron ugotować zgodnie z instrukcją na opakowaniu.",
        "Kurczaka pokroić w paski i usmażyć na oliwie.",
        "Połączyć makaron z kurczakiem i pesto, dokładnie wymieszać.",
      ],
      calories: 520,
      protein: 45,
      fat: 20,
      carbs: 50,
      incomplete: false,
    },
    {
      meal_type: "dinner",
      recipe_name: "Tosty z awokado i jajkiem",
      ingredients: [
        { name: "Chleb pełnoziarnisty", quantity: "60 g", measure: "2 kromki" },
        { name: "Awokado", quantity: "100 g", measure: "0.5 sztuki" },
        { name: "Jajo kurze", quantity: "50 g", measure: "1 średnie" },
      ],
      instructions: [
        "Chleb podpiec w tosterze na chrupiąco.",
        "Awokado rozgnieść widelcem i rozsmarować na tostach.",
        "Jajko ugotować na miękko lub twardo i pokroić w plastry, położyć na awokado.",
      ],
      calories: 420,
      protein: 18,
      fat: 25,
      carbs: 40,
      incomplete: false,
    },
    {
      meal_type: "breakfast",
      recipe_name: "Słodki omlet kokosowy z bananem i jagodami",
      ingredients: [
        { name: "Jajo kurze", quantity: "150 g", measure: "3 średnie sztuki" },
        { name: "Mąka kokosowa", quantity: "50 g", measure: "50 g" },
      ],
      instructions: [
        "W misce roztrzepać jajka z mąką kokosową, napojem i szczypką soli, aż masa będzie jednolita.",
        "Na rozgrzaną patelnię z oliwą wylać masę jajeczną.",
        "Na wierzchu ułożyć plasterki banana i jagody.",
      ],
      calories: 695,
      protein: 29,
      fat: 36,
      carbs: 66,
      incomplete: false,
    },
    {
      meal_type: "lunch",
      recipe_name: "Grillowany kurczak z warzywami",
      ingredients: [
        { name: "Pierś z kurczaka", quantity: "200 g", measure: "1 sztuka" },
        { name: "Papryka czerwona", quantity: "100 g", measure: "1 sztuka" },
        { name: "Cukinia", quantity: "150 g", measure: "0.5 sztuki" },
        { name: "Oliwa z oliwek", quantity: "10 ml", measure: "1 łyżka" },
      ],
      instructions: [
        "Kurczaka przyprawić solą, pieprzem i oliwą.",
        "Grillować kurczaka oraz pokrojone warzywa na średnim ogniu przez 10 minut.",
        "Podawać na ciepło z sosem jogurtowym.",
      ],
      calories: 450,
      protein: 55,
      fat: 12,
      carbs: 15,
      incomplete: false,
    },
    {
      meal_type: "dinner",
      recipe_name: "Sałatka z tuńczykiem i jajkiem",
      ingredients: [
        {
          name: "Tuńczyk w sosie własnym",
          quantity: "120 g",
          measure: "1 puszka",
        },
        { name: "Jajo kurze", quantity: "100 g", measure: "2 średnie sztuki" },
        { name: "Sałata lodowa", quantity: "50 g", measure: "kilka liści" },
        { name: "Oliwa z oliwek", quantity: "10 ml", measure: "1 łyżka" },
      ],
      instructions: [
        "Jajka ugotować na twardo i pokroić w ćwiartki.",
        "Tuńczyka odsączyć z zalewy.",
        "Wszystkie składniki połączyć, skropić oliwą i podawać.",
      ],
      calories: 350,
      protein: 40,
      fat: 18,
      carbs: 8,
      incomplete: false,
    },
    {
      meal_type: "lunch",
      recipe_name: "Makaron pełnoziarnisty z pesto i kurczakiem",
      ingredients: [
        {
          name: "Makaron pełnoziarnisty",
          quantity: "100 g",
          measure: "1 porcja",
        },
        { name: "Pierś z kurczaka", quantity: "150 g", measure: "1 sztuka" },
        { name: "Pesto bazyliowe", quantity: "30 g", measure: "2 łyżki" },
      ],
      instructions: [
        "Makaron ugotować zgodnie z instrukcją na opakowaniu.",
        "Kurczaka pokroić w paski i usmażyć na oliwie.",
        "Połączyć makaron z kurczakiem i pesto, dokładnie wymieszać.",
      ],
      calories: 520,
      protein: 45,
      fat: 20,
      carbs: 50,
      incomplete: false,
    },
    {
      meal_type: "dinner",
      recipe_name: "Tosty z awokado i jajkiem",
      ingredients: [
        { name: "Chleb pełnoziarnisty", quantity: "60 g", measure: "2 kromki" },
        { name: "Awokado", quantity: "100 g", measure: "0.5 sztuki" },
        { name: "Jajo kurze", quantity: "50 g", measure: "1 średnie" },
      ],
      instructions: [
        "Chleb podpiec w tosterze na chrupiąco.",
        "Awokado rozgnieść widelcem i rozsmarować na tostach.",
        "Jajko ugotować na miękko lub twardo i pokroić w plastry, położyć na awokado.",
      ],
      calories: 420,
      protein: 18,
      fat: 25,
      carbs: 40,
      incomplete: false,
    },
  ];
};
